"""SQLAlchemy engine + table definitions for VittaMantri's Supabase Postgres backend."""

from __future__ import annotations

import os

from dotenv import load_dotenv
from sqlalchemy import (
    BigInteger,
    Column,
    Date,
    ForeignKey,
    Identity,
    MetaData,
    Numeric,
    Table,
    Text,
    Time,
    TIMESTAMP,
    create_engine,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import CITEXT, UUID

# db.py is imported before main.py's own load_dotenv() call, so load it here too —
# harmless if .env was already loaded (idempotent) or if real env vars are already
# set by systemd's EnvironmentFile in production.
load_dotenv()

# Supabase's transaction-mode pooler (port 6543) doesn't preserve session state
# across statements, so psycopg3's server-side prepared statement cache must be
# disabled — otherwise queries intermittently fail with
# "prepared statement ... does not exist".
engine = create_engine(
    os.environ["DATABASE_URL"],
    pool_size=3,
    max_overflow=2,
    pool_pre_ping=True,
    pool_recycle=300,
    connect_args={"prepare_threshold": None},
)

metadata = MetaData()

# `GENERATED BY DEFAULT AS IDENTITY` (not `ALWAYS`) so both the one-off Postgres
# migration and auth.py's save_users() "full list upsert" compatibility layer can
# insert explicit, pre-existing ids without needing OVERRIDING SYSTEM VALUE.
households = Table(
    "households",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False, server_default=func.now()),
)

users = Table(
    "users",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("household_id", BigInteger, ForeignKey("households.id"), nullable=False),
    Column("username", CITEXT, nullable=False, unique=True),
    Column("display_name", Text, nullable=False),
    Column("password_hash", Text, nullable=False),
    Column("telegram_id", BigInteger, unique=True),
    Column("role", Text, nullable=False),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False, server_default=func.now()),
)

transactions = Table(
    "transactions",
    metadata,
    Column("id", UUID(as_uuid=False), primary_key=True, server_default=text("gen_random_uuid()")),
    Column("household_id", BigInteger, ForeignKey("households.id"), nullable=False),
    Column("date", Date, nullable=False),
    Column("time", Time, nullable=False),
    Column("amount", Numeric(12, 2), nullable=False),
    Column("type", Text, nullable=False),
    Column("category", Text, nullable=False),
    Column("subcategory", Text, nullable=False, server_default=""),
    Column("description", Text, nullable=False, server_default=""),
    Column("source", Text, nullable=False, server_default=""),
    Column("logged_by", Text, nullable=False, server_default="Unknown"),
    Column("logged_by_id", BigInteger, nullable=False, server_default="0"),
    Column("input_method", Text, nullable=False, server_default="text"),
    Column("raw_input", Text, nullable=False, server_default=""),
    Column("created_at", TIMESTAMP(timezone=True), nullable=False, server_default=func.now()),
)

custom_categories = Table(
    "custom_categories",
    metadata,
    Column("household_id", BigInteger, ForeignKey("households.id"), primary_key=True),
    Column("name", Text, primary_key=True),
    Column("emoji", Text, nullable=False, server_default="🏷️"),
)

custom_subcategories = Table(
    "custom_subcategories",
    metadata,
    Column("household_id", BigInteger, ForeignKey("households.id"), primary_key=True),
    Column("category_name", Text, primary_key=True),
    Column("name", Text, primary_key=True),
)

deleted_categories = Table(
    "deleted_categories",
    metadata,
    Column("household_id", BigInteger, ForeignKey("households.id"), primary_key=True),
    Column("name", Text, primary_key=True),
)
